### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by eggsactly** [reynico/arduino-wardriving#1]
I forked your repo and made modifications, which is a massive grey area for projects without a license. Can you add an open source license of your choice to your repo?
 Something like BSD or GPL would be great!

**Comment by eggsactly** [comment]
If I don't hear back about this issue by April 1st, 2018 I issue a GPLv3 license to my fork.

**Comment by reynico** [comment]
Hey, sorry for the delay. I'm a bit overloaded with work. I'll add a GPL one, thanks

**Comment by reynico** [comment]
Done sir, thanks for the message, the effort, and the fork.

**Comment by eggsactly** [comment]
Thank you!
